/*
 Generated by typeshare 1.13.4
*/

/** JSON value from Rust `serde_json::Value` (typeshare placeholder). */
export type Value = unknown;

export interface AgentCancelRequest {
  requestId: string;
}

export interface AgentChannelActionRequest {
  action: string;
  channel: string;
  config?: Record<string, Value>;
}

export interface AgentChannelActionResponse {
  channelType: string;
}

export interface AgentChannelField {
  key: string;
  label: string;
  type: string;
  value: string;
  defaultValue?: string;
  placeholder?: string;
}

export interface AgentChannelDetail {
  name: string;
  labelKey: string;
  active: boolean;
  fields: AgentChannelField[];
  hintKey?: string;
}

export interface AgentChannelSummary {
  name: string;
  active: boolean;
  label: string;
}

export interface AgentClearProviderRequest {
  providerId: string;
}

export interface ModelProviderItem {
  /** `config.json` `bot_type` id (e.g. `deepseek`, `openai`). */
  id: string;
  configured: boolean;
  isActive: boolean;
}

export interface ModelProviderDetail {
  id: string;
  configured: boolean;
  isActive: boolean;
  apiBase?: string;
  apiBaseDefault?: string;
  hasApiBase: boolean;
  apiKeyMasked?: string;
  models: string[];
  botTypeValue: string;
  editable: boolean;
}

export interface ToolItem {
  name: string;
  description: string;
  isMcp: boolean;
}

export interface SkillItem {
  name: string;
  description: string;
  enabled: boolean;
  source: string;
}

export interface AgentConsoleState {
  sessionId: string;
  workspaceDir: string;
  modelName: string;
  botType: string;
  providers: ModelProviderItem[];
  providerDetails: ModelProviderDetail[];
  tools: ToolItem[];
  skills: SkillItem[];
  mcpStatus: Record<string, string>;
  configPath?: string;
  temperature?: number;
  topP?: number;
  requestTimeout?: number;
}

export interface AgentGetSkillDetailRequest {
  name: string;
}

export interface AgentInstallSkillRequest {
  source: string;
}

export interface AgentKnowledgeFile {
  path: string;
  title: string;
}

export interface AgentKnowledgeGraphNode {
  id: string;
  label: string;
  category: string;
}

export interface AgentKnowledgeGraphLink {
  source: string;
  target: string;
}

export interface AgentKnowledgeGraph {
  nodes: AgentKnowledgeGraphNode[];
  links: AgentKnowledgeGraphLink[];
}

export interface AgentKnowledgeIngestError {
  file: string;
  message: string;
}

export interface AgentKnowledgeIngestItem {
  path: string;
  title: string;
  category: string;
  slug: string;
  originalName: string;
  truncated: boolean;
  charCount: number;
  archive: string;
}

/** Request for the picker command (category only; dialog is shown on Rust side). */
export interface AgentKnowledgePickUploadRequest {
  category?: string;
}

export interface AgentKnowledgeReadRequest {
  path: string;
}

export interface AgentKnowledgeReadResult {
  path: string;
  content: string;
}

export interface AgentKnowledgeUploadFile {
  filename: string;
  data: number[];
}

export interface AgentKnowledgeUploadRequest {
  files: AgentKnowledgeUploadFile[];
  category?: string;
}

export interface AgentKnowledgeUploadResult {
  results: AgentKnowledgeIngestItem[];
  errors: AgentKnowledgeIngestError[];
  count: number;
  memorySynced: boolean;
}

export interface AgentLogStreamPayload {
  type: string;
  content?: string;
  message?: string;
}

export interface AgentLogStreamState {
  started: boolean;
}

export interface AgentLogsStatus {
  enabled: boolean;
  source: string;
}

export interface AgentMemoryItem {
  filename: string;
  itemType: string;
  size: number;
  updatedAt: string;
}

export interface AgentMemoryReadRequest {
  filename: string;
}

export interface AgentMemoryReadResult {
  filename: string;
  content: string;
}

export interface AgentReadLogsRequest {
  limit?: number;
}

export interface AgentReadLogsResult {
  source: string;
  content: string;
}

export interface AgentRunFinished {
  requestId: string;
  error?: string;
  content?: string;
}

export interface AgentSendMessageRequest {
  message: string;
  sessionId?: string;
}

export interface AgentSendMessageResponse {
  requestId: string;
  sessionId: string;
}

export interface AgentSessionSummary {
  id: string;
  title: string;
  updatedAt: string;
}

export interface AgentSetChatModelRequest {
  providerId?: string;
  model?: string;
}

/** SSE-style chunk emitted during `agent_send_message` (`agent/stream-chunk`). */
export interface AgentStreamChunk {
  requestId: string;
  type: string;
  content?: string;
  tool?: string;
  arguments?: Value;
  status?: string;
  result?: string;
  executionTime?: number;
}

export interface AgentTaskSummary {
  id: string;
  name: string;
  enabled: boolean;
  nextRunAt?: string;
}

export interface AgentUpdateProviderRequest {
  providerId: string;
  apiKey?: string;
  apiBase?: string;
  apiBaseSet?: boolean;
}

export interface AppSession {
  currentLanguage: string;
}

export interface InstallSkillResult {
  installed_names: string[];
  source: string;
}

export interface LicenseStatusDto {
  machineCode: string;
  valid: boolean;
  reason?: string;
}

export interface SkillDetail {
  name: string;
  description: string;
  enabled: boolean;
  source: string;
  filePath: string;
  baseDir: string;
  disableModelInvocation: boolean;
}
