/*
 Generated by typeshare 1.13.4
*/

/** JSON value from Rust `serde_json::Value` (typeshare placeholder). */
export type Value = unknown;

export interface AgentCancelRequest {
  requestId: string;
}

export interface AgentChannelActionRequest {
  action: string;
  channel: string;
  config?: Record<string, Value>;
}

export interface AgentChannelActionResponse {
  channelType: string;
}

export interface AgentChannelField {
  key: string;
  label: string;
  type: string;
  value: string;
  defaultValue?: string;
  placeholder?: string;
}

export interface AgentChannelDetail {
  name: string;
  label: string;
  active: boolean;
  fields: AgentChannelField[];
  hint?: string;
}

export interface AgentChannelSummary {
  name: string;
  active: boolean;
  label: string;
}

export interface AgentClearProviderRequest {
  providerId: string;
}

export interface ModelProviderItem {
  id: string;
  configured: boolean;
  isActive: boolean;
}

export interface ModelProviderDetail {
  id: string;
  configured: boolean;
  isActive: boolean;
  apiBase?: string;
  apiBaseDefault?: string;
  hasApiBase: boolean;
  apiKeyMasked?: string;
  models: string[];
  botTypeValue: string;
  editable: boolean;
}

export interface ToolItem {
  name: string;
  label: string;
  description: string;
  isMcp: boolean;
}

export interface SkillItem {
  name: string;
  description: string;
  enabled: boolean;
  source: string;
}

export interface AgentConsoleState {
  sessionId: string;
  workspaceDir: string;
  modelName: string;
  botType: string;
  providers: ModelProviderItem[];
  providerDetails: ModelProviderDetail[];
  tools: ToolItem[];
  skills: SkillItem[];
  mcpStatus: Record<string, string>;
  configPath?: string;
  temperature?: number;
  topP?: number;
  requestTimeout?: number;
}

export interface AgentGetSkillDetailRequest {
  name: string;
}

export interface AgentInstallSkillRequest {
  source: string;
}

export interface AgentKnowledgeFile {
  path: string;
  title: string;
}

export interface AgentKnowledgeGraphNode {
  id: string;
  label: string;
  category: string;
}

export interface AgentKnowledgeGraphLink {
  source: string;
  target: string;
}

export interface AgentKnowledgeGraph {
  nodes: AgentKnowledgeGraphNode[];
  links: AgentKnowledgeGraphLink[];
}

export interface AgentKnowledgeIngestError {
  file: string;
  message: string;
}

export interface AgentKnowledgeIngestItem {
  path: string;
  title: string;
  category: string;
  slug: string;
  originalName: string;
  truncated: boolean;
  charCount: number;
  archive: string;
}

/** Request for the picker command (category only; dialog is shown on Rust side). */
export interface AgentKnowledgePickUploadRequest {
  category?: string;
}

export interface AgentKnowledgeReadRequest {
  path: string;
}

export interface AgentKnowledgeReadResult {
  path: string;
  content: string;
}

export interface AgentKnowledgeUploadFile {
  filename: string;
  data: number[];
}

export interface AgentKnowledgeUploadRequest {
  files: AgentKnowledgeUploadFile[];
  category?: string;
}

export interface AgentKnowledgeUploadResult {
  results: AgentKnowledgeIngestItem[];
  errors: AgentKnowledgeIngestError[];
  count: number;
  memorySynced: boolean;
}

export interface AgentLogStreamPayload {
  type: string;
  content?: string;
  message?: string;
}

export interface AgentLogStreamState {
  started: boolean;
}

export interface AgentLogsStatus {
  enabled: boolean;
  source: string;
}

export interface AgentMemoryItem {
  filename: string;
  itemType: string;
  size: number;
  updatedAt: string;
}

export interface AgentMemoryReadRequest {
  filename: string;
}

export interface AgentMemoryReadResult {
  filename: string;
  content: string;
}

export interface AgentReadLogsRequest {
  limit?: number;
}

export interface AgentReadLogsResult {
  source: string;
  content: string;
}

export interface AgentReplyNodeConfig {
  promptTemplate: string;
  skillFilter?: string[];
  clearHistory?: boolean;
  outputKey?: string;
}

export interface AgentRunFinished {
  requestId: string;
  error?: string;
  content?: string;
}

export interface AgentSendMessageRequest {
  message: string;
  sessionId?: string;
}

export interface AgentSendMessageResponse {
  requestId: string;
  sessionId: string;
}

export interface AgentSessionSummary {
  id: string;
  title: string;
  updatedAt: string;
}

export interface AgentSetChatModelRequest {
  providerId?: string;
  model?: string;
}

export interface AgentStreamChunk {
  requestId: string;
  type: string;
  content?: string;
  tool?: string;
  arguments?: Value;
  status?: string;
  result?: string;
  executionTime?: number;
}

export interface AgentTaskSummary {
  id: string;
  name: string;
  enabled: boolean;
  nextRunAt?: string;
}

export interface AgentUpdateProviderRequest {
  providerId: string;
  apiKey?: string;
  apiBase?: string;
  apiBaseSet?: boolean;
}

export interface BranchNodeConfig {
  /** 简单 MVP：按 context key 的布尔值选边；完整表达式 T003+。 */
  conditionKey: string;
}

export interface DelayNodeConfig {
  durationSecs?: number;
  untilKey?: string;
}

export interface HumanAndsignNodeConfig {
  prompt: string;
  timeoutSecs?: number;
}

export interface InstallSkillResult {
  installed_names: string[];
  source: string;
}

export interface LicenseStatusDto {
  machineCode: string;
  valid: boolean;
  reason?: string;
}

export interface ToolCallNodeConfig {
  toolName: string;
  arguments?: Value;
  outputKey?: string;
}

/** 节点类型相关配置（按 `kind` 选用对应字段）。 */
export interface NodeConfig {
  agentReply?: AgentReplyNodeConfig;
  toolCall?: ToolCallNodeConfig;
  humanAndsign?: HumanAndsignNodeConfig;
  branch?: BranchNodeConfig;
  delay?: DelayNodeConfig;
}

export interface SkillDetail {
  name: string;
  description: string;
  enabled: boolean;
  source: string;
  filePath: string;
  baseDir: string;
  disableModelInvocation: boolean;
}

/** MVP 首批节点类型。 */
export enum NodeKind {
  AgentReply = "agent_reply",
  ToolCall = "tool_call",
  HumanAndsign = "human_andsign",
  Branch = "branch",
  Delay = "delay"
}

/** 节点单次执行状态（Step 内）。 */
export enum StepStatus {
  Queued = "queued",
  Active = "active",
  Suspended = "suspended",
  Completed = "completed",
  Failed = "failed"
}

/** 单步执行记录。 */
export interface StepRecord {
  id: string;
  nodeId: string;
  nodeKind: NodeKind;
  status: StepStatus;
  startedAt: string;
  finishedAt?: string;
  input?: Value;
  output?: Value;
  error?: string;
}

/** 有向边；`condition` 为 `Some` 时表示分支出边（与 `branch` 节点配合）。 */
export interface Transition {
  from: string;
  to: string;
  condition?: string;
  label?: string;
}

/** Run 级变量表（分支、节点输出、渠道元数据）。 */
export interface WorkflowContext {
  vars?: Record<string, Value>;
}

/** 图节点。 */
export interface WorkflowNode {
  id: string;
  kind: NodeKind;
  label?: string;
  config: NodeConfig;
}

/** 工作流定义：静态节点图。 */
export interface WorkflowDefinition {
  id: string;
  name: string;
  version: number;
  entryNodeId: string;
  nodes: WorkflowNode[];
  transitions: Transition[];
}

export interface WorkflowGetRunRequest {
  runId: string;
}

export interface WorkflowResumeRequest {
  runId: string;
}

/** Run 级执行状态。 */
export enum RunStatus {
  Pending = "pending",
  Running = "running",
  WaitingHuman = "waiting_human",
  Paused = "paused",
  Succeeded = "succeeded",
  Failed = "failed",
  Cancelled = "cancelled"
}

/** 一次工作流执行实例。 */
export interface WorkflowRun {
  id: string;
  definitionId: string;
  status: RunStatus;
  currentNodeId?: string;
  context: WorkflowContext;
  steps: StepRecord[];
  createdAt: string;
  updatedAt: string;
  sessionId?: string;
  error?: string;
}

export interface WorkflowStartRequest {
  definitionId: string;
  input?: Value;
  sessionId?: string;
}

export interface WorkflowStartResponse {
  runId: string;
}

export enum ChannelAdapterCapability {
  Connect = "connect",
  Disconnect = "disconnect",
  ListConversations = "list_conversations",
  Send = "send",
  OnMessage = "on_message",
  Health = "health"
}

export enum ChannelTypeId {
  Wework = "wework"
}

/** 节点在 Run 内的瞬时状态（executor 内部使用，可选持久化）。 */
export enum NodeState {
  Idle = "idle",
  Queued = "queued",
  Active = "active",
  Suspended = "suspended",
  Completed = "completed",
  Failed = "failed"
}
